saadpasta/developerFolio

src/components/blogCard/BlogCard.css, src/components/header/Header.css, src/containers/achievement/Achievement.css, src/containers/blogs/Blog.css, src/containers/contact/Contact.css, src/containers/greeting/Greeting.css, src/containers/projects/Project.css, src/containers/skills/Skills.css, src/index.css
Closes #5
**Before:**
<kbd>![developerFolio-before](https://user-images.githubusercontent.com/36920441/68530086-e98a0a80-0326-11ea-90cc-5e5e54f5f01a.gif)</kbd>
**After:**
<kbd>![developerFolio-after](https://user-images.githubusercontent.com/36920441/68530093-f0188200-0326-11ea-8a07-e0bfd6a9d9de.gif)</kbd>
=> Better padding and font size for medium resolutions

src/assests/images/talksCardBack.svg, src/assests/images/talksCardBackAlt.svg, src/components/blogCard/BlogCard.css, src/components/talkCard/TalkCard.css, src/components/talkCard/TalkCard.js, src/containers/blogs/Blog.css, src/containers/greeting/Greeting.js, src/portfolio.js
Remade the old talks section into a new rectangle card.
See screenshots below for updated design:
Responsive design:
=> Re-design talks section, better fix color scheme

src/containers/contact/Contact.css, src/containers/contact/Contact.js
=> Adds appropriate href to contact section

src/components/button/Button.css
=> Fixes btn overlap on screen width 320px

README.md, dockerFile
Hello i have added a docker file in developerfolio now if someone clone this project they don't need to install node js version manually docker will do that .
Docker commands for building and running image .
BUILD IMAGE : `docker build -t developerfolio:latest .`
RUN IMAGE: `docker run -p 3000:3000 developerfolio:latest`
#slimcoder
=> Dockerized developerFolio

src/portfolio.js
Currently, our website is not secure because we are loading image from HTTP to fix this I have a loaded an image from https.
close #56
=> Fix website not secure

src/containers/greeting/Greeting.css, src/containers/greeting/Greeting.js, src/portfolio.js
Add Wave animation in wave emoji in Greeting Section. To attract user when they are viewing the portfolio.
=> Animation In Wave Emoji

src/containers/topbutton/Top.css
Removed comments (thanks for adding them though Naveen!)
Add hover transition
Used black instead of grey to look more consistent
=> Removed comments, add transition, color

README.md, package.json, src/components/header/Header.js, src/containers/Main.js, src/containers/twitter-embed/twitter.css, src/containers/twitter-embed/twitter.js, src/portfolio.js
I have added a Twitter Timeline as suggested in the issue.
Fixes #63
Things Changed.
1.  Added Twitter component,
2.  Necessary updates for it in Readme file.
3. Added Deploy To Netlify Button in the readme file.
=> Added Twitter Timeline

package.json, src/components/footer/Footer.js, src/components/githubRepoCard/GithubRepoCard.js, src/components/header/Header.js, src/containers/StartupProjects/StartupProject.js, src/containers/achievement/Achievement.js, src/containers/blogs/Blogs.js, src/containers/contact/Contact.js, src/containers/greeting/Greeting.js, src/containers/podcast/Podcast.js, src/containers/projects/Projects.js, src/containers/skillProgress/skillProgress.js, src/containers/skills/Skills.js, src/containers/talks/Talks.js, src/containers/twitter-embed/twitter.js
Fresh PR as a duplicate of #74 .  
@saadpasta and @kartik918 , Please review.
=> Added Basic Reveal Fade animations

LICENSE
=> Switch license to GPLv3

src/components/blogCard/BlogCard.css, src/components/blogCard/BlogCard.js, src/containers/blogs/Blog.css, src/portfolio.js
Updated Blog Card With New Design that matches our theme.
=> Update : Blog Card With New Design

src/portfolio.js
I changed description into subtitle in achievement-cards in portfolio.js
Since,it is not working.
=> Changed description into subtitle in achievement-cards

src/containers/projects/Projects.js
=> Using socialMediaLinks.github in href of MORE PROJECTS button

src/components/header/Header.js, src/components/socialMedia/SocialMedia.css, src/components/socialMedia/SocialMedia.js, src/portfolio.js
- Created a customisable name logo for the header in portfolio.js.
- The social media icons won't show up if their links are not provided by the user.
- Fixed some minor spelling and grammatical mistakes.
=> Solves issue #120 and some minor changes.

README.md
This fixes #132. Improve documentation.
This PR is about adding documentation on hosting using GitHub pages.
=> Add info on hosting using GitHub Pages in ReadMe file.

src/portfolio.js
Add my Github Username to show my profile instead of undefined.
=> Update Github UserName 

.gitignore, README.md, src/containers/projects/Projects.js, src/portfolio.js
Currently, we are pushing our GitHub token to git which is not a good practice. And our scenario is really confusing. 
This PR fixes this issue and #162 one also.
=> Add : Functionality to get Github token from .env

src/components/blogCard/BlogCard.js
=> Redirect to blog url on button click

src/containers/talks/Talks.css, src/containers/talks/Talks.js
=> Change talks alignment to horizontal

src/components/blogCard/BlogCard.css
=> Issue #157 - Blog Card Layout

src/components/githubRepoCard/GithubRepoCard.js, src/containers/projects/Project.css
#123 
1. Reduce the font-size of the title
2. Increased the height and width of the icon size of the repo.
=> Updated Open-Source UI

README.md, package.json, src/components/githubProfileCard/GithubProfileCard.js, src/containers/profile/Profile.js
=> Remove : Axios and Replace API call with GraphQl

package-lock.json, src/components/button/Button.css
#156 
- Added the animations in the .main-button and .main-button:hover class.
=> Updated outward button transition

src/components/header/Header.css
Fixed the issue that caused safari letters switching, resolves #199
=> Fixed the ligature issue on safari

.github/workflows/node.js.yml, README.md, src/components/footer/Footer.js, src/components/socialMedia/SocialMedia.css, src/components/socialMedia/SocialMedia.js, src/portfolio.js
- node.js.yml: add inline commenting for GitHub Secret references
- README.md: update documentation for configuring GitHub Actions workflow for GitHub Pages
- Footer.js: add footer text reference to developerFolio.  This is just good to give reference to the project.  Many of the other projects that are popular for personal sites do this such as beautiful-jekyll.
- SocialMedia.js: add stackoverflow and medium icons
- portfolio.js: add stackoverflow and medium links
=> Medium, Stackoverflow, GitHub Actions

.github/workflows/node.js.yml
Update nodejs,yml according to this https://github.com/saadpasta/developerFolio/pull/228#discussion_r471113652
=> Update node.js.yml [Important]

src/components/header/Header.css
Fixes for the #230 Issue
Preview
https://www.loom.com/share/f9fc5f7e6e58496d83c9381ff407e922
=> Fixes for Saad Pasta name medium size viewport

README.md
Hi all,
I just discovered this amazing repository and I am planning to use it for my portfolio. While reading through README file, I noticed some improvements on styles/wording can be made. Please review my changes and let me know what you think of it.
Definitely looking forward to contributing to this repo in the near future!
=> Improve readability and minor style changes in Readme

src/components/githubRepoCard/GithubRepoCard.js
First of all, thank you for a good project.
I had faced the same issue as issue #218 
It has already been a closed issue, but I want to share the code as I solved this problem with the following code modifications.
=> Resolving a repository connection error where the language used is not defined

README.md
#239 I had to remove the emojis from some headings because they couldn't be included in the internal link. 
However, if the emojis are necessary then i can use anchor tags to name the sections and then link them.
=> Table of Contents added to README.md

src/containers/achievement/Achievement.js
=> Hot Fix : Fix Spelling Error in achievementsCards.js

src/containers/education/Education.js
I was unable to toggle the "education" section
=> Bug Fix in Education Container

src/components/educationCard/EducationCard.css
Fixed height to remove the issue - school name text not displaying to full height
=> Fixed School Text Height

README.md
Resolved #292 
- The screen capture GIF was changed and updated in README
- Included GIF in both dark and light themes.
=> Changed screen capture GIF

README.md, src/components/ToggleSwitch/ToggleSwitch.js, src/containers/Main.js
saving the theme user already selected so next time that theme will be appeared
=> feat: storing theme in local storage

src/components/achievementCard/AchievementCard.css, src/components/githubRepoCard/GithubRepoCard.css
Resolves Issue #306.
Added smooth transition to github cards and also box-shadow in dark mode.
Added box-shadow to achievement cards in dark mode.
=> Add shadow on hover to all cards.

package-lock.json, src/components/experienceCard/ExperienceCard.js, src/components/githubRepoCard/GithubRepoCard.js, src/components/header/Header.js, src/components/socialMedia/SocialMedia.js
Fixed some package vulnerabilities and React warnings. One package, `react-scripts`, has a major version update that has breaking changes so I have knowingly left it out. 
Updating that package without knowing the full extent of changes would be a bad decision (and one I'm avoiding right now).
=> Run npm audit fix, manually fix some warnings

src/portfolio.js
The email address variable is wrong it in the contact info section of `src/portfolio.js`
=> [FIX]Email variable in contactInfo section

.github/workflows/node.js.yml
see https://github.com/saadpasta/developerFolio/pull/333#issuecomment-792270471
=> fix(node.js.yml): set GITHUB_USERNAME env var

.github/workflows/node.js.yml, fetch.js
raise an error when corresponding env vars aren't set
See https://github.com/saadpasta/developerFolio/pull/334#issuecomment-792272372
=> CI: use the token provided from Github

fetch.js, package-lock.json, package.json
Hi, I had issues loading the .env variables which resolved in undefined, I resolved with this
=> fix(fetch.js): load .env variables

README.md
about #333
fixes #342
encourage using Github Actions more about #226 because that would simply things
=> docs: add info about the new profile setup

src/components/githubProfileCard/GithubProfileCard.js
Check for `prof.isHireable` instead.
Fix https://github.com/saadpasta/developerFolio/issues/358
=> `prof.hireable` isn't defined

.github/workflows/node.js.yml, README.md, env.example, fetch.js, package-lock.json, package.json, src/App.test.js, src/components/displayLottie/DisplayLottie.js, src/components/header/Header.js, src/containers/education/Education.js, src/setupTests.js
This PR resolves #349 by fixing missing test dependencies, jest configs and fixing test errors.
Also moved the GitHub profile fetch script behind an env key which is set to false as default. 
Reason for moving fetch request behind a key is to help setup first dev environment faster and without crashes so new users don't feel discouraged. This would also emphasize properly setting up env variables.
=> Fix tests and test errors, move gh fetch request behind env key

.github/workflows/deploy.yml
it was removed by mistake in https://github.com/saadpasta/developerFolio/commit/b5e870a622db3a92f0b0c23668ded4e333f1f86a
Fixes https://github.com/saadpasta/developerFolio/issues/387
=> Re-add deploy action

src/components/socialMedia/SocialMedia.js
changing the email logo to envelope, this will make it more clear for others to understand that the button is for email
=> Changed the email logo

README.md
Fixes #404 
This change requires a documentation update
=> Added instructions to customize Lottie animations in the readme

.github/workflows/deploy.yml, .gitignore, README.md, src/containers/blogs/Blogs.js
Setting displayMediumBlogs to true breaks since there are no fetched blogs.
=> Fix fallback for medium blogs

src/App.scss, src/components/achievementCard/AchievementCard.scss, src/components/blogCard/BlogCard.scss, src/components/button/Button.scss, src/index.css
Fixes #456 
I change the font size form px to rem.
The size is same but the unit is different.
Visually every thing looks the same as stated in the issue.
=> Changed font size from px to rem

src/components/githubRepoCard/GithubRepoCard.js
This PR fixed browser console warnings:
> Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?
=> Fix invalid fill-rule property name.

src/components/githubRepoCard/GithubRepoCard.js, src/components/githubRepoCard/sizeConversion.js, src/utils.js
Added repo size conversion to GitHub repo cards closes #525
=> Added repo size conversion to github repo cards.

src/containers/blogs/Blogs.js
Add additional methods to extract blogs' text content within paragraph tags'.And it was tested.
Fixes #709
=> fix:Incomplete string escaping or encoding #709
