.gitignore
README.md
package-lock.json
package.json
src/components/footer/Footer.js
src/containers/greeting/Greeting.js
src/portfolio.js

Fixes #3 
I have fixed emoji render issue. From now on if the user needs to enter any emoji in `protofolio.js`, the user should pass it as a parameter in `emoji()`. This solves the issue as it converts the emoji to an image so there is no problem.

Fixed emoji-render-issue using react-easy-emoji

---

README.md

Removed portfolio.gif by moving it to Github CDN. Reduces around 8mb in size.

Optimized repo size

---

src/components/githubRepoCard/GithubRepoCard.js
src/containers/projects/Projects.js
src/portfolio.js

PinnedRepositories has been deprecated and has been removed from graphql query of Github. So currently we can't get pinned repo's from Github. I came to when I opened `saadpasta.github.io` and can't view my GitHub Projects.
The [changelog](https://developer.github.com/v4/changelog/2019-03-30-schema-changes/) for GitHub GraphQL schema (2019-03-30) mentions that the pinnedRepositories will be deprecated or removed by 2019-07-01. GraphQL API users are requested to use ProfileOwner.pinneditems instead. 
This has been fixed and we can view this API call on `saadpasta.github.io` it has been fixed there. 
`{
user(login: "saadpasta") {
pinnedItems(first: 6, types: [REPOSITORY]) {
totalCount
edges {
node {
... on Repository {
name
description
forkCount
stargazers {
totalCount
}
url
id
diskUsage …

Update : GraphQl Query from pinnedRepositories to pinnedItems (Important)

---

README.md

This is much-awaited documentation.
Fixes #218

Update link to Open Source Projects in Readme

---

src/components/button/Button.css
src/components/githubProfileCard/GithubProfileCard.css
src/components/socialMedia/SocialMedia.css

- Reversed github profile image shadow, shadow removes on hover now and matches the other cards aesthetic.
- Fixed `project-button` not being centered on screen.
- 'Hover-out' transitions for social media icons (should've been done in #156)

Layout and CSS fixes

---

src/components/ToggleSwitch/ToggleSwitch.css

I came across the following inconsistency caused by the 'hidden' checkbox behind the slider being visible.
A nit in the design but certainly visible on click.
Wrote a minor quickfix that won't mess up any of our PRs.

Fix dark mode slider checkbox being visible

---

src/components/talkCard/TalkCard.css

Fixed a minor inconsistency in dark mode shadow for talk card.
Before:
After:

Fix talk card box shadow

---

src/components/githubRepoCard/GithubRepoCard.css

Fixed repo-name height in repo card

Fixed name height in repo card

---

src/components/githubProfileCard/GithubProfileCard.js

The Location icon (from github profile) was not changing to a suitable color in the dark mode, so added -> stroke to fix that along with size and placement updates, hope this is useful.

Dark Mode Fix

---

package-lock.json
package.json
src/portfolio.js

Fixed a formatting error in master, this should also fix the failing check in other PRs like #365.

Prettier version bump

---

src/components/achievementCard/AchievementCard.js
src/components/achievementCard/AchivementCard.js
src/components/blogCard/BlogCard.js
src/components/githubRepoCard/GithubRepoCard.js
src/containers/StartupProjects/StartupProject.js

Hi, I was working on the achivementCard.js file to invalidate `window.open` action gets empty. Thought it will be okay to PR.
There are couple of things to point out here.
#1
First what I found as trouble here was that not always you have url for a specific tag, or specific card.
Sometimes you just want to place keywords. 
Not link to somewhere.
Even the master branch had some empty urls. 
Made me realize it IS okay to not have urls sometimes.
Below are cases I tested and worked out alright.
1. with actual url
2. with empty string as url property
3. no url property 
#2
Second, some onClick callbacks did not even match the function names, So I fixed em up also.
#3
Lastly, I really appreciate your project.
Lemme know if anything,
cheers from Seoul, Korea

FIX : unintended opening of urls

---

package.json
src/_globalColor.scss
src/components/socialMedia/SocialMedia.js
src/components/socialMedia/SocialMedia.scss
src/containers/greeting/Greeting.js
src/portfolio.js

Resolves #405 
- Add support for Kaggle social link in `socialMediaLinks`.
- Hide resume button if no `resumeLink` or empty value is found
- Fixed autoprefixer warnings in the logs
Screenshot of the new icon:

Add support for Kaggle social link, hide resumeLink on empty value

---

public/index.html

When using the template, I was unable to display the **rust** language logo.
Font-awesome version in the template is `5.13`. Updating to latest stable `5.15` solved the problem.
PR created to be able to display the icons that came after `5.13`

Update Font Awesome CDN from version 5.13 to 5.15

---

README.md
env.example
fetch.js
src/containers/blogs/Blogs.js
src/portfolio.js

I've added this for my personal blog and I think it would be a nice feature.
See output for my medium account (costin.canciu - https://medium.com/@costin.canciu):
The hardcoded blogs will still be displayed if the medium user account is not set in portofolio.js.

Added medium blogs fetch feature for blogs section

---

README.md

Currently, github data for one's profile isn't fetched unless we add `USE_GITHUB_DATA = "true"` to the `.env` file. Maybe adding this line in the documentation might be helpful.

docs: add USE_GITHUB_DATA = "true" to the .env file in documentation

---

src/components/githubRepoCard/GithubRepoCard.scss

Fixed the colour of the icon in the GitHub repo card.
Currently, the colour of the GitHub repo card icon doesn't change when we change to dark mode. 
After this fix, the icons' colour will change to white just like the text on the card.

Github RepoCard Icon Color

---

src/components/educationCard/EducationCard.js

Just added a simple check for school logo.
Without the check if the user doesn't give a logo, then it would render something weird which is not good. As discussed in #521

Check for School Logo and Render

---

src/components/achievementCard/AchievementCard.scss
src/containers/StartupProjects/StartupProjects.scss

Centering image vertically in achievement card and big project section. If an image used in achievement card or big project is landscape (width is more than height) the image doesn't aligns vertically centered. By using flex we can center images vertically and horizontally.
Before:
After:

center image vertically

---

src/components/ToggleSwitch/ToggleSwitch.js
src/components/ToggleSwitch/ToggleSwitch.scss

- Add icons ☀️, 🌜 for light and dark mode respectively

feat: add icon for dark and light theme

---

README.md

GitHub seems to have launched a beta version of fine-grained tokens, but this project requires the classic tokens to setup. This PR updates the README to make it clearer for the users to choose the classic token instead of the beta fine-grained tokens.

Update README.md on generating github token

---

README.md
package-lock.json
package.json
src/components/displayLottie/DisplayLottie.js

fix(ci): fix build failing due to old (and deprecated) packages

---

.github/workflows/deploy.yml
.github/workflows/prettier.yml

fixed prettier for CI builds failing due to node 12.x updated the github action setup-node to latest
Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.
Fixes #632

fix(ci): fix prettier

---

.github/workflows/deploy.yml
.github/workflows/prettier.yml

Bumped up the node-version to 18.x for github workflows

fix(ci): update workflow to use node 18.x

---

src/containers/greeting/Greeting.js
src/containers/greeting/Greeting.scss

Fixed: Resume button in nav bar not redirecting to "DOWNLOAD MY RESUME" button.
Fixes  (#737)

Fix: Resume button in nav bar
